services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    image: "postgres:15"
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  libapp:
    build: ./library/
    command: sh -c "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"
    volumes:
      - ./library:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - MEDIA_DOMAIN=${MEDIA_DOMAIN}
    networks:
      - app-network


  celery:
    build: ./library/
    command: celery -A library worker --loglevel=info
    depends_on:
      - redis
      - postgres
    volumes:
      - ./library:/app
    environment:
      - MEDIA_DOMAIN=${MEDIA_DOMAIN}
    networks:
      - app-network

  celery-beat:
    build: ./library/
    command: celery -A library beat --loglevel=info
    depends_on:
      - redis
      - postgres
    volumes:
      - ./library:/app
    environment:
      - MEDIA_DOMAIN=${MEDIA_DOMAIN}
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
